name: ECR-Lifecycle-Manager
description: Deletes old images from an Amazon ECR repository, optionally limiting deletion to untagged images.
author: Agung Widhiatmojo
branding:
  icon: 'archive'
  color: 'black'
inputs:
  repo_name:
    description: 'The name of the ECR repository to delete images from.'
    required: true
  num_to_keep:
    description: 'The number of latest images to keep.'
    required: false
    default: 10
  dry_run:
    description: 'Perform a dry run without actually deleting images.'
    required: false
    default: true
  delete_untagged_images:
    description: 'Delete only untagged images.'
    required: false
    default: false
runs:
  using: 'composite'
  steps:
    - name: Set Greeting
      run: echo "Hello $repo_name."
      shell: bash
      env:
        repo_name: ${{ inputs.repo_name }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3

